# Generated by Django 4.2.2 on 2024-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrecord",
            name="address",
            field=models.CharField(max_length=80),
        ),
    ]
